version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev        
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Bookmark volume (do not map location)
      - .:/app # Take everything from current directory (except bookmarked volume) and map to /app      